Rails.application.config.assets.precompile += %w( properties/general.js )
Rails.application.config.assets.precompile += %w( properties/edit.js )
Rails.application.config.assets.precompile += %w( devise/registrations/edit_form.js )
Rails.application.config.assets.precompile += %w( vendor/modernizr.js )
Rails.application.config.assets.precompile += %w( properties/calendar.js )
Rails.application.config.assets.precompile += %w( properties/map.js )